/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario.Graphic;

import inventario.Entity.Producto;
import inventario.Logic.CONFIG_FORMS;
import inventario.Logic.LogicController;
import inventario.Logic.MyTableModel;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author David
 */
public class FrmAdministracion extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdministracion
     */
    public FrmAdministracion() {
        initComponents();
        
        initForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpAdministracion = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbInformeCostos_Anio = new javax.swing.JComboBox<>();
        pnInformeCostos_GraficoContainer = new javax.swing.JPanel();
        lbInformeCostos_Chart = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbTop10Producto_Chart = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbTop10Productos_Mes = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInformacionInventario_Productos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtInformacionProveedores_Codigo = new javax.swing.JTextField();
        pnInformacionProveedores_Container = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbInformacionProveedores_Proveedores = new javax.swing.JTable();
        btInformacionProveedores_Consultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Administración");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tpAdministracion.setBackground(new java.awt.Color(255, 255, 255));
        tpAdministracion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpAdministracionStateChanged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Año:");

        cbInformeCostos_Anio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbInformeCostos_AnioActionPerformed(evt);
            }
        });

        pnInformeCostos_GraficoContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnInformeCostos_GraficoContainer.setBorder(javax.swing.BorderFactory.createTitledBorder("Gráfico"));

        javax.swing.GroupLayout pnInformeCostos_GraficoContainerLayout = new javax.swing.GroupLayout(pnInformeCostos_GraficoContainer);
        pnInformeCostos_GraficoContainer.setLayout(pnInformeCostos_GraficoContainerLayout);
        pnInformeCostos_GraficoContainerLayout.setHorizontalGroup(
            pnInformeCostos_GraficoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInformeCostos_GraficoContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbInformeCostos_Chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnInformeCostos_GraficoContainerLayout.setVerticalGroup(
            pnInformeCostos_GraficoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInformeCostos_GraficoContainerLayout.createSequentialGroup()
                .addComponent(lbInformeCostos_Chart, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnInformeCostos_GraficoContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbInformeCostos_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbInformeCostos_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnInformeCostos_GraficoContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpAdministracion.addTab("Informe de Costos", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gráfico"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTop10Producto_Chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbTop10Producto_Chart, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText("Mes:");

        cbTop10Productos_Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTop10Productos_MesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTop10Productos_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTop10Productos_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpAdministracion.addTab("Producto más utilizado", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de productos"));

        tbInformacionInventario_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbInformacionInventario_Productos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpAdministracion.addTab("Información de Inventario", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Código de producto:");

        pnInformacionProveedores_Container.setBackground(new java.awt.Color(255, 255, 255));
        pnInformacionProveedores_Container.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de proveedores"));

        tbInformacionProveedores_Proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbInformacionProveedores_Proveedores);

        javax.swing.GroupLayout pnInformacionProveedores_ContainerLayout = new javax.swing.GroupLayout(pnInformacionProveedores_Container);
        pnInformacionProveedores_Container.setLayout(pnInformacionProveedores_ContainerLayout);
        pnInformacionProveedores_ContainerLayout.setHorizontalGroup(
            pnInformacionProveedores_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInformacionProveedores_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        pnInformacionProveedores_ContainerLayout.setVerticalGroup(
            pnInformacionProveedores_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnInformacionProveedores_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        btInformacionProveedores_Consultar.setText("Consultar");
        btInformacionProveedores_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInformacionProveedores_ConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInformacionProveedores_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btInformacionProveedores_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnInformacionProveedores_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtInformacionProveedores_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btInformacionProveedores_Consultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnInformacionProveedores_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpAdministracion.addTab("Información de Proveedores", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpAdministracion)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpAdministracion)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(769, 514));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        CONFIG_FORMS.frmMain.show();
        this.hide();
    }//GEN-LAST:event_formWindowClosing

    private void cbInformeCostos_AnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInformeCostos_AnioActionPerformed
        // TODO add your handling code here:
        if(cbInformeCostos_Anio.getSelectedIndex() > 0)
        {
            BufferedImage biChart = LogicController.getChart_InformeCostos(cbInformeCostos_Anio.getSelectedItem().toString(), lbInformeCostos_Chart.getWidth(), lbInformeCostos_Chart.getHeight());
            if(biChart != null)
            {
                lbInformeCostos_Chart.setIcon(new ImageIcon(biChart));
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error al generar el reporte de informe de costos", "Generar reporte", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cbInformeCostos_AnioActionPerformed

    private void tpAdministracionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpAdministracionStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tpAdministracionStateChanged

    private void cbTop10Productos_MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTop10Productos_MesActionPerformed
        // TODO add your handling code here:
        if(cbTop10Productos_Mes.getSelectedIndex() > 0)
        {
            BufferedImage biChart = LogicController.getChart_Top10Productos(cbTop10Productos_Mes.getSelectedItem().toString(), lbTop10Producto_Chart.getWidth(), lbTop10Producto_Chart.getHeight());
            if(biChart != null)
            {
                lbTop10Producto_Chart.setIcon(new ImageIcon(biChart));
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error al generar el reporte de productos más vendidos", "Generar reporte", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_cbTop10Productos_MesActionPerformed

    private void btInformacionProveedores_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInformacionProveedores_ConsultarActionPerformed
        // TODO add your handling code here:
        
        if(txtInformacionProveedores_Codigo.getText().length() > 1)
        {
            Producto producto = LogicController.getProductoByCodigo(txtInformacionProveedores_Codigo.getText());
            if(producto != null)
            {
                MyTableModel dbMtm = LogicController.getProveedoresByProducto(producto.getCodigo());

                if(displayInformacionProveedores(dbMtm) == true)
                {
                    TitledBorder titledBorder = BorderFactory.createTitledBorder("Lista de proveedores para \"" + producto.getNombre() + "\" (código: " + producto.getCodigo() + ")");
                    pnInformacionProveedores_Container.setBorder(titledBorder);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error al mostrar el reporte de proveedores", "Generar reporte", JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "No se ha encontrado el producto con código \"" + txtInformacionProveedores_Codigo.getText() + "\"", "Generar reporte", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar el código del producto a consultar", "Generar reporte", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btInformacionProveedores_ConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministracion().setVisible(true);
            }
        });
    }

    
    /*
    *
    *   C O D E
    *
    */
    
    private void initForm()
    {
        this.getContentPane().setBackground(Color.WHITE);
    }
    
    public void clearForms()
    {
       clearForm_InformeCostos();
       clearForm_Top10Productos();
       clearForm_InformacionInventario();
       clearForm_InformacionProveedores();
    }
    
    private void clearForm_InformeCostos()
    {
        int year = Calendar.getInstance().get(Calendar.YEAR);
        
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        dcbm.addElement("Seleccione..");
        for(int i=year; i>year-5; i--)
        {
            dcbm.addElement(i);
        }
        
        cbInformeCostos_Anio.setModel(dcbm);
        
        lbInformeCostos_Chart.setIcon(null);
    }
    
    private void clearForm_Top10Productos()
    {
        Calendar cal = Calendar.getInstance(); 
        cal.setTime(new Date());
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM");
        
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        dcbm.addElement("Seleccione..");
        for(int i=0; i<12; i++)
        {
            dcbm.addElement(dateFormat.format(cal.getTime()));
            
            cal.add(Calendar.MONTH, -1);
        }
        
        cbTop10Productos_Mes.setModel(dcbm);
        
        lbTop10Producto_Chart.setIcon(null);
    }
    
    private boolean clearForm_InformacionInventario()
    {
        MyTableModel dbMtm = LogicController.getProductos();
        if(dbMtm == null)
        {
            return false;
        }
        
        boolean result = false;
        
        MyTableModel mtm = new MyTableModel();
        mtm.addColumn("Código");
        mtm.addColumn("Producto");
        mtm.addColumn("Clasificación");
        mtm.addColumn("Fecha caducidad");
        mtm.addColumn("Cantidad");
        
        Object[] data = null;

        for(int i=0; i<dbMtm.getRowCount(); i++)
        {
            data = new Object[5];
            data[0] = dbMtm.getValueAt(i, 0).toString();
            data[1] = dbMtm.getValueAt(i, 1).toString();
            data[2] = dbMtm.getValueAt(i, 2).toString();
            data[3] = dbMtm.getValueAt(i, 3).toString();
            data[4] = dbMtm.getValueAt(i, 4).toString();

            mtm.addRow(data);
        }
        
        tbInformacionInventario_Productos.setModel(mtm);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        
        tbInformacionInventario_Productos.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tbInformacionInventario_Productos.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tbInformacionInventario_Productos.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tbInformacionInventario_Productos.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tbInformacionInventario_Productos.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        
        return result;
    }
    
    private void clearForm_InformacionProveedores()
    {
        txtInformacionProveedores_Codigo.setText("");
        
        MyTableModel mtm = new MyTableModel();
        mtm.addColumn("RUT");
        mtm.addColumn("Proveedor");
        mtm.addColumn("Precio");
        mtm.addColumn("Cantidad");
        mtm.addColumn("Factura");
        mtm.addColumn("Fecha");
        
        tbInformacionProveedores_Proveedores.setModel(mtm);
    }
    
    private boolean displayInformacionProveedores(MyTableModel dbMtm)
    {
        if(dbMtm == null)
        {
            return false;
        }
        
        MyTableModel mtm = new MyTableModel();
        mtm.addColumn("RUT");
        mtm.addColumn("Proveedor");
        mtm.addColumn("Precio");
        mtm.addColumn("Cantidad");
        mtm.addColumn("Factura");
        mtm.addColumn("Fecha");
        
        Object[] data = null;

        for(int i=0; i<dbMtm.getRowCount(); i++)
        {
            data = new Object[6];
            data[0] = dbMtm.getValueAt(i, 0).toString();
            data[1] = dbMtm.getValueAt(i, 1).toString();
            data[2] = dbMtm.getValueAt(i, 2).toString();
            data[3] = dbMtm.getValueAt(i, 3).toString();
            data[4] = dbMtm.getValueAt(i, 4).toString();
            data[5] = dbMtm.getValueAt(i, 5).toString();

            mtm.addRow(data);
        }
        
        tbInformacionProveedores_Proveedores.setModel(mtm);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        
        tbInformacionProveedores_Proveedores.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tbInformacionProveedores_Proveedores.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tbInformacionProveedores_Proveedores.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tbInformacionProveedores_Proveedores.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tbInformacionProveedores_Proveedores.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        tbInformacionProveedores_Proveedores.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInformacionProveedores_Consultar;
    private javax.swing.JComboBox<String> cbInformeCostos_Anio;
    private javax.swing.JComboBox<String> cbTop10Productos_Mes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbInformeCostos_Chart;
    private javax.swing.JLabel lbTop10Producto_Chart;
    private javax.swing.JPanel pnInformacionProveedores_Container;
    private javax.swing.JPanel pnInformeCostos_GraficoContainer;
    private javax.swing.JTable tbInformacionInventario_Productos;
    private javax.swing.JTable tbInformacionProveedores_Proveedores;
    private javax.swing.JTabbedPane tpAdministracion;
    private javax.swing.JTextField txtInformacionProveedores_Codigo;
    // End of variables declaration//GEN-END:variables
}
