/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario.Graphic;

import inventario.Entity.Producto;
import inventario.Entity.Proveedor;
import inventario.Logic.CONFIG_FORMS;
import inventario.Logic.LogicController;
import inventario.Logic.MyTableModel;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author David
 */
public class FrmCompras extends javax.swing.JFrame {

    private ArrayList<String> listProductos_Codigo;
    /**
     * Creates new form FrmCompras
     */
    public FrmCompras() {
        initComponents();
        
        initForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbProducto_Nombre = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtProducto_Clasificacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProducto_PrecioCompra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtProducto_Cantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtProducto_NumeroFactura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtProducto_FechaCompra = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtProveedor_Nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtProveedor_RUT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtProveedor_Direccion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtProveedor_Telefono = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtProveedor_Celular = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtProveedor_Email = new javax.swing.JTextField();
        btFindProveedor = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btInsertCompra = new javax.swing.JButton();
        btRemoveProveedor = new javax.swing.JButton();
        btBack = new javax.swing.JButton();

        setTitle("Compras");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        jLabel1.setText("Nombre:");

        cbProducto_Nombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbProducto_NombreItemStateChanged(evt);
            }
        });
        cbProducto_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProducto_NombreActionPerformed(evt);
            }
        });

        jLabel2.setText("Clasificación:");

        txtProducto_Clasificacion.setEditable(false);

        jLabel3.setText("Precio de compra:");

        jLabel4.setText("Cantidad:");

        jLabel5.setText("Número de factura:");

        jLabel6.setText("Fecha de compra:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProducto_PrecioCompra, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtProducto_Clasificacion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbProducto_Nombre, javax.swing.GroupLayout.Alignment.TRAILING, 0, 221, Short.MAX_VALUE)
                            .addComponent(txtProducto_Cantidad, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProducto_NumeroFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(txtProducto_FechaCompra))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbProducto_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProducto_Clasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtProducto_PrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProducto_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtProducto_NumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtProducto_FechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedor"));

        jLabel7.setText("Nombre:");

        jLabel8.setText("RUT:");

        txtProveedor_RUT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProveedor_RUTFocusLost(evt);
            }
        });

        jLabel9.setText("Dirección:");

        jLabel10.setText("Teléfono:");

        jLabel11.setText("Celular:");

        jLabel12.setText("Email:");

        btFindProveedor.setText("Buscar");
        btFindProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFindProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProveedor_RUT)
                    .addComponent(txtProveedor_Direccion)
                    .addComponent(txtProveedor_Celular)
                    .addComponent(txtProveedor_Telefono)
                    .addComponent(txtProveedor_Email)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtProveedor_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btFindProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtProveedor_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFindProveedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtProveedor_RUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtProveedor_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtProveedor_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtProveedor_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtProveedor_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btInsertCompra.setText("Guardar compra");
        btInsertCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertCompraActionPerformed(evt);
            }
        });

        btRemoveProveedor.setText("Eliminar proveedor");
        btRemoveProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveProveedorActionPerformed(evt);
            }
        });

        btBack.setText("Volver");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btRemoveProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btInsertCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btBack, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btInsertCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRemoveProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBack)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(408, 681));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        CONFIG_FORMS.frmMain.show();
        this.hide();
    }//GEN-LAST:event_formWindowClosing

    private void cbProducto_NombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbProducto_NombreItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProducto_NombreItemStateChanged

    private void cbProducto_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProducto_NombreActionPerformed
        // TODO add your handling code here:
        if(cbProducto_Nombre.getSelectedIndex() > 0)
        {
            Producto producto = LogicController.getProductoByCodigo(this.listProductos_Codigo.get(cbProducto_Nombre.getSelectedIndex() -1));
            if(producto != null)
            {
                txtProducto_Clasificacion.setText(producto.getClasificacion());
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error al consultar el producto", "Eliminar producto", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            txtProducto_Clasificacion.setText("");
        }
    }//GEN-LAST:event_cbProducto_NombreActionPerformed

    private void txtProveedor_RUTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProveedor_RUTFocusLost
        // TODO add your handling code here:
        txtProveedor_RUT.setText(formatRUT(txtProveedor_RUT.getText()));
    }//GEN-LAST:event_txtProveedor_RUTFocusLost

    private void btFindProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFindProveedorActionPerformed
        // TODO add your handling code here:
        String rut = JOptionPane.showInputDialog(this, "Ingrese el RUT del proveedor", "Buscar proveedor", JOptionPane.QUESTION_MESSAGE);
        if(rut != null)
        {
            rut = formatRUT(rut);
            if(rut.length() > 0)
            {
                Proveedor proveedor = LogicController.getProveedorByRUT(rut);
                if(proveedor != null)
                {
                    displayProveedor(proveedor);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "No se ha encontrado el proveedor con RUT \"" + rut + "\"", "Buscar proveedor", JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "El RUT ingresado es inválido", "Buscar proveedor", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar el RUT del proveedor a buscar", "Buscar proveedor", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btFindProveedorActionPerformed

    private void btRemoveProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveProveedorActionPerformed
        // TODO add your handling code here:
        String rut = JOptionPane.showInputDialog(this, "Ingrese el RUT del proveedor", "Eliminar proveedor", JOptionPane.QUESTION_MESSAGE);
        if(rut != null)
        {
            rut = formatRUT(rut);
            if(rut.length() > 0)
            {
                int response = LogicController.isProveedorInOrden(rut);

                switch(response)
                {
                    case -2:
                    {
                        JOptionPane.showMessageDialog(this, "Ha ocurrido un error al consultar el proveedor", "Eliminar proveedor", JOptionPane.ERROR_MESSAGE);

                        break;
                    }

                    case -1:
                    {
                        JOptionPane.showMessageDialog(this, "El proveedor que intentas eliminar no existe", "Eliminar proveedor", JOptionPane.WARNING_MESSAGE);

                        break;
                    }

                    case 0:
                    {
                        boolean executed = LogicController.deleteProveedor(rut);

                        if(executed == true)
                        {
                            JOptionPane.showMessageDialog(this, "Se ha eliminado exitosamente el proveedor", "Eliminar proveedor", JOptionPane.INFORMATION_MESSAGE);

                            loadProductos();
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al eliminar el proveedor", "Eliminar proveedor", JOptionPane.ERROR_MESSAGE);
                        }

                        break;
                    }

                    case 1:
                    {
                        JOptionPane.showMessageDialog(this, "No se puede eliminar el proveedor porque está registrado en una compra", "Eliminar proveedor", JOptionPane.WARNING_MESSAGE);

                        break;
                    }

                    default:
                    {
                        break;
                    }
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "El RUT ingresado es inválido", "Eliminar proveedor", JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar el RUT del proveedor a eliminar", "Eliminar proveedor", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btRemoveProveedorActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        CONFIG_FORMS.frmMain.show();
        this.hide();
    }//GEN-LAST:event_btBackActionPerformed

    private void btInsertCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertCompraActionPerformed
        // TODO add your handling code here:
        if((validateFormProducto()) && (validateFormProveedor()))
        {
            boolean executed = LogicController.insertCompra(
                                                            this.listProductos_Codigo.get(cbProducto_Nombre.getSelectedIndex() - 1),
                                                            txtProveedor_RUT.getText(), 
                                                            txtProveedor_Nombre.getText(), 
                                                            txtProveedor_Direccion.getText(), 
                                                            txtProveedor_Telefono.getText(), 
                                                            txtProveedor_Celular.getText(), 
                                                            txtProveedor_Email.getText(), 
                                                            txtProducto_PrecioCompra.getText(), 
                                                            txtProducto_Cantidad.getText(), 
                                                            txtProducto_NumeroFactura.getText(), 
                                                            txtProducto_FechaCompra.getText()
            );
            
            if(executed == true)
            {
                JOptionPane.showMessageDialog(this, "Se ha ingresado exitosamente la nueva compra", "Ingresar nueva compra", JOptionPane.INFORMATION_MESSAGE);

                clearFormCompra();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error al ingresar la nueva compra", "Ingresar nueva compra", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btInsertCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCompras().setVisible(true);
            }
        });
    }

    
    /*
    *
    *   C O D E
    *
    */
    
    private void initForm()
    {
        this.getContentPane().setBackground(Color.WHITE);
    }
    
    public void loadProductos()
    {
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        
        MyTableModel dbMtm = LogicController.getProductos();
        
        if(dbMtm != null)
        {
            this.listProductos_Codigo = new ArrayList<String>();
            dcbm.addElement("Seleccione..");

            for(int i=0; i<dbMtm.getRowCount(); i++)
            {
                this.listProductos_Codigo.add(dbMtm.getValueAt(i, 0).toString());
                dcbm.addElement(dbMtm.getValueAt(i, 1).toString());
            }
        }
        else
        {
            
        }
        
        cbProducto_Nombre.setModel(dcbm);
    }
    
    private boolean validateNumber(String s)
    {
        try
        {
            int i = Integer.parseInt(s);
            if(i >= 0)
            {
                return true;
            }
            
            return false;
        }
        catch(Exception ex)
        {
            return false;
        }
    }
    
    private String formatRUT(String s)
    {
        s = s.replace(".", "").replace("-", "");
        
        String rut = "";
        
        if((validateNumber(s)) && (s.length() > 1))
        {
           rut = s.substring(0, s.length() -1) + "-" + s.substring(s.length() -1, s.length());
        }
        
        return rut;
    }
    
    private boolean validateRUT(String s)
    {
        return formatRUT(s).length() > 0;
    }
    
    private void displayProveedor(Proveedor proveedor)
    {
        if(proveedor != null)
        {
            txtProveedor_Nombre.setText(proveedor.getNombre());
            txtProveedor_RUT.setText(proveedor.getRUT());
            txtProveedor_Direccion.setText(proveedor.getDireccion());
            txtProveedor_Telefono.setText(proveedor.getTelefono());
            txtProveedor_Celular.setText(proveedor.getCelular());
            txtProveedor_Email.setText(proveedor.getEmail());
        }
    }
    
    private boolean validateFormProducto()
    {
        boolean response = true;
        
        if(cbProducto_Nombre.getSelectedIndex() < 1)
        {
            JOptionPane.showMessageDialog(this, "Debes seleccionar el producto", "Ingresar nueva compra", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(txtProducto_PrecioCompra.getText().length() < 1)
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar el precio de compra del producto", "Ingresar nueva compra", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(validateNumber(txtProducto_PrecioCompra.getText()) == false)
        {
            JOptionPane.showMessageDialog(this, "El precio de compra de producto debe ser numérico positivo", "Ingresar nueva compra", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(txtProducto_Cantidad.getText().length() < 1)
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar la cantidad del producto", "Ingresar nueva compra", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(validateNumber(txtProducto_Cantidad.getText()) == false)
        {
            JOptionPane.showMessageDialog(this, "La cantidad del producto debe ser numérica positiva", "Ingresar nueva compra", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(txtProducto_NumeroFactura.getText().length() < 1)
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar el número de factura del producto", "Ingresar nueva compra", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(validateNumber(txtProducto_NumeroFactura.getText()) == false)
        {
            JOptionPane.showMessageDialog(this, "El número de factura del producto debe ser numérico positivo", "Ingresar nueva compra", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(txtProducto_FechaCompra.getText().length() < 1)
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar la fecha de compra del producto", "Ingresar nueva compra", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        
        
        return response;
    }
    
    private boolean validateFormProveedor()
    {
        boolean response = true;
        
        if(txtProveedor_Nombre.getText().length() < 1)
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar el nombre del proveedor", "Ingresar nueva compra", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(txtProveedor_RUT.getText().length() < 1)
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar el RUT del proveedor", "Ingresar nueva compra", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(validateRUT(txtProveedor_RUT.getText()) == false)
        {
            JOptionPane.showMessageDialog(this, "El RUT ingresado para el proveedo debe ser válido", "Ingresar nueva compra", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(txtProveedor_Direccion.getText().length() < 1)
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar la dirección del proveedor", "Ingresar nueva compra", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(txtProveedor_Telefono.getText().length() < 1)
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar el teléfono del proveedor", "Ingresar nueva compra", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(txtProveedor_Celular.getText().length() < 1)
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar el celular del proveedor", "Ingresar nueva compra", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(txtProveedor_Email.getText().length() < 1)
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar el email del proveedor", "Ingresar nueva compra", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        
     
        return response;
    }
    
    private void clearFormCompra()
    {
        loadProductos();
        txtProducto_Clasificacion.setText("");
        txtProducto_PrecioCompra.setText("");
        txtProducto_Cantidad.setText("");
        txtProducto_NumeroFactura.setText("");
        txtProducto_FechaCompra.setText("");
        
        txtProveedor_Nombre.setText("");
        txtProveedor_RUT.setText("");
        txtProveedor_Direccion.setText("");
        txtProveedor_Telefono.setText("");
        txtProveedor_Celular.setText("");
        txtProveedor_Email.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btFindProveedor;
    private javax.swing.JButton btInsertCompra;
    private javax.swing.JButton btRemoveProveedor;
    private javax.swing.JComboBox<String> cbProducto_Nombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtProducto_Cantidad;
    private javax.swing.JTextField txtProducto_Clasificacion;
    private javax.swing.JTextField txtProducto_FechaCompra;
    private javax.swing.JTextField txtProducto_NumeroFactura;
    private javax.swing.JTextField txtProducto_PrecioCompra;
    private javax.swing.JTextField txtProveedor_Celular;
    private javax.swing.JTextField txtProveedor_Direccion;
    private javax.swing.JTextField txtProveedor_Email;
    private javax.swing.JTextField txtProveedor_Nombre;
    private javax.swing.JTextField txtProveedor_RUT;
    private javax.swing.JTextField txtProveedor_Telefono;
    // End of variables declaration//GEN-END:variables
}
