/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario.Graphic;

import inventario.Logic.CONFIG_FORMS;
import inventario.Logic.LogicController;
import inventario.Logic.MyTableModel;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author David
 */
public class FrmProductos extends javax.swing.JFrame {

    /**
     * Creates new form FrmProductos
     */
    public FrmProductos() {
        initComponents();
        
        initForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbClasificacion = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtFechaCaducidad = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btFind = new javax.swing.JButton();
        btInsert = new javax.swing.JButton();
        btRemove = new javax.swing.JButton();
        btBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Productos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de productos"));

        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbProductos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Producto"));

        jLabel1.setText("Nombre:");

        jLabel5.setText("Clasificación:");

        cbClasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..", "Aseo", "Cocina" }));

        jLabel6.setText("Código:");

        jLabel7.setText("Fecha de caducidad:");

        txtFechaCaducidad.setText("2017-10-09");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbClasificacion, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombre)
                    .addComponent(txtFechaCaducidad, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFechaCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btFind.setText("Buscar");
        btFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFindActionPerformed(evt);
            }
        });

        btInsert.setText("Ingresar nuevo producto");
        btInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertActionPerformed(evt);
            }
        });

        btRemove.setText("Eliminar");
        btRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveActionPerformed(evt);
            }
        });

        btBack.setText("Volver");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btRemove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btInsert, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(btBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btFind)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(640, 486));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        CONFIG_FORMS.frmMain.show();
        this.hide();
    }//GEN-LAST:event_formWindowClosing

    private void btFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFindActionPerformed
        // TODO add your handling code here:
        
        String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre del producto", "Buscar producto", JOptionPane.QUESTION_MESSAGE);
        if(nombre != null)
        {
            MyTableModel dbMtm = LogicController.getProductos(nombre);
            if(dbMtm != null)
            {
                displayProductos(dbMtm);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error al realizar la búsqueda", "Buscar producto", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar parte del nombre del producto a buscar", "Buscar producto", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btFindActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void btInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertActionPerformed
        // TODO add your handling code here:
        if(validateFormProducto())
        {
            boolean executed = LogicController.insertProducto(
                                                                txtCodigo.getText(),
                                                                txtNombre.getText(), 
                                                                cbClasificacion.getSelectedItem().toString(), 
                                                                txtFechaCaducidad.getText()
            );
            
            if(executed == true)
            {
                JOptionPane.showMessageDialog(this, "Se ha ingresado exitosamente el nuevo producto", "Ingresar nuevo producto", JOptionPane.INFORMATION_MESSAGE);

                loadProductos();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error al ingresar el nuevo producto", "Ingresar nuevo producto", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btInsertActionPerformed

    private void btRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog(this, "Ingrese el código del producto", "Eliminar producto", JOptionPane.QUESTION_MESSAGE);
        if(codigo != null)
        {
            int response = LogicController.isProductoInOrden(codigo);
            
            switch(response)
            {
                case -2:
                {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error al consultar el producto", "Eliminar producto", JOptionPane.ERROR_MESSAGE);
                    
                    break;
                }
                
                case -1:
                {
                    JOptionPane.showMessageDialog(this, "El producto que intentas eliminar no existe", "Eliminar producto", JOptionPane.WARNING_MESSAGE);
                    
                    break;
                }
                
                case 0:
                {
                    boolean executed = LogicController.deleteProducto(codigo);

                    if(executed == true)
                    {
                        JOptionPane.showMessageDialog(this, "Se ha eliminado exitosamente el producto", "Eliminar producto", JOptionPane.INFORMATION_MESSAGE);

                        loadProductos();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Ha ocurrido un error al eliminar el producto", "Eliminar producto", JOptionPane.ERROR_MESSAGE);
                    }
                
                    break;
                }
                
                case 1:
                {
                    JOptionPane.showMessageDialog(this, "No se puede eliminar el producto porque está registrado en una compra", "Eliminar producto", JOptionPane.WARNING_MESSAGE);
                    
                    break;
                }
                
                default:
                {
                    break;
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar el código del producto a eliminar", "Eliminar producto", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btRemoveActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        CONFIG_FORMS.frmMain.show();
        this.hide();
    }//GEN-LAST:event_btBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProductos().setVisible(true);
            }
        });
    }

    /*
    *
    *   C O D E
    *
    */
    
    private void initForm()
    {
        this.getContentPane().setBackground(Color.WHITE);
    }
    
    public void loadProductos()
    {
        displayProductos(LogicController.getProductos());
    }
    
    private boolean displayProductos(MyTableModel dbMtm)
    {
        if(dbMtm == null)
        {
            return false;
        }
        
        boolean result = false;
        
        MyTableModel mtm = new MyTableModel();
        mtm.addColumn("Código");
        mtm.addColumn("Producto");
        mtm.addColumn("Clasificación");
        mtm.addColumn("Fecha caducidad");
        mtm.addColumn("Cantidad");
        
        if(dbMtm != null)
        {
            Object[] data = null;
            
            for(int i=0; i<dbMtm.getRowCount(); i++)
            {
                data = new Object[5];
                data[0] = dbMtm.getValueAt(i, 0).toString();
                data[1] = dbMtm.getValueAt(i, 1).toString();
                data[2] = dbMtm.getValueAt(i, 2).toString();
                data[3] = dbMtm.getValueAt(i, 3).toString();
                data[4] = dbMtm.getValueAt(i, 4).toString();
                
                mtm.addRow(data);
            }
        }
        else
        {
            
        }
        
        tbProductos.setModel(mtm);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(DefaultTableCellRenderer.CENTER);
        
        tbProductos.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tbProductos.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tbProductos.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tbProductos.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tbProductos.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        
        return result;
    }
    
    private boolean validateFormProducto()
    {
        boolean response = true;
        
        if(txtNombre.getText().length() < 1)
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar el nombre del producto", "Ingresar nuevo producto", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(cbClasificacion.getSelectedIndex() < 1)
        {
            JOptionPane.showMessageDialog(this, "Debes seleccionar la clasificación del producto", "Ingresar nuevo producto", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(txtCodigo.getText().length() < 1)
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar el código del producto", "Ingresar nuevo producto", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(txtFechaCaducidad.getText().length() < 1)
        {
            JOptionPane.showMessageDialog(this, "Debes ingresar la fecha de caducidad del producto", "Ingresar nuevo producto", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(LogicController.getProductoByNombre(txtNombre.getText()) != null)
        {
            JOptionPane.showMessageDialog(this, "Ya existe un producto con el nombre ingresado (" + txtNombre.getText() + ")", "Ingresar nuevo producto", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        else if(LogicController.getProductoByCodigo(txtCodigo.getText()) != null)
        {
            JOptionPane.showMessageDialog(this, "Ya existe un producto con el código ingresado (" + txtCodigo.getText() + ")", "Ingresar nuevo producto", JOptionPane.WARNING_MESSAGE);
            
            response = false;
        }
        
        return response;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btFind;
    private javax.swing.JButton btInsert;
    private javax.swing.JButton btRemove;
    private javax.swing.JComboBox<String> cbClasificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProductos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtFechaCaducidad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
